/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public class MediaFormatVector extends java.util.AbstractList<MediaFormat> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MediaFormatVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MediaFormatVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_MediaFormatVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MediaFormatVector(MediaFormat[] initialElements) {
    this();
    reserve(initialElements.length);

    for (MediaFormat element : initialElements) {
      add(element);
    }
  }

  public MediaFormatVector(Iterable<MediaFormat> initialElements) {
    this();
    for (MediaFormat element : initialElements) {
      add(element);
    }
  }

  public MediaFormat get(int index) {
    return doGet(index);
  }

  public MediaFormat set(int index, MediaFormat e) {
    return doSet(index, e);
  }

  public boolean add(MediaFormat e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, MediaFormat e) {
    modCount++;
    doAdd(index, e);
  }

  public MediaFormat remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public MediaFormatVector() {
    this(pjsua2JNI.new_MediaFormatVector__SWIG_0(), true);
  }

  public MediaFormatVector(MediaFormatVector other) {
    this(pjsua2JNI.new_MediaFormatVector__SWIG_1(MediaFormatVector.getCPtr(other), other), true);
  }

  public long capacity() {
    return pjsua2JNI.MediaFormatVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    pjsua2JNI.MediaFormatVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return pjsua2JNI.MediaFormatVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    pjsua2JNI.MediaFormatVector_clear(swigCPtr, this);
  }

  public MediaFormatVector(int count, MediaFormat value) {
    this(pjsua2JNI.new_MediaFormatVector__SWIG_2(count, MediaFormat.getCPtr(value), value), true);
  }

  private int doSize() {
    return pjsua2JNI.MediaFormatVector_doSize(swigCPtr, this);
  }

  private void doAdd(MediaFormat x) {
    pjsua2JNI.MediaFormatVector_doAdd__SWIG_0(swigCPtr, this, MediaFormat.getCPtr(x), x);
  }

  private void doAdd(int index, MediaFormat x) {
    pjsua2JNI.MediaFormatVector_doAdd__SWIG_1(swigCPtr, this, index, MediaFormat.getCPtr(x), x);
  }

  private MediaFormat doRemove(int index) {
    long cPtr = pjsua2JNI.MediaFormatVector_doRemove(swigCPtr, this, index);
    return (cPtr == 0) ? null : new MediaFormat(cPtr, false);
  }

  private MediaFormat doGet(int index) {
    long cPtr = pjsua2JNI.MediaFormatVector_doGet(swigCPtr, this, index);
    return (cPtr == 0) ? null : new MediaFormat(cPtr, false);
  }

  private MediaFormat doSet(int index, MediaFormat val) {
    long cPtr = pjsua2JNI.MediaFormatVector_doSet(swigCPtr, this, index, MediaFormat.getCPtr(val), val);
    return (cPtr == 0) ? null : new MediaFormat(cPtr, false);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    pjsua2JNI.MediaFormatVector_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
